learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),

]

learning_logs/urls.py
"""Definiuje wzorce adresow URL dla learning_logs."""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
	#Strona glowna
	path('', views.index, name='index'),
	#Wyswietlanie wszystkich tematow
	path('topics/', views.topics, name='topics'),
	#Strona szczegolowa dotyzaca pojedynczego tematu
	path('topics/(<int:topic_id>)/', views.topic, name='topic'),
	#Strona do dodawania tematow przez uzytkownika
	path('new_topic/', views.new_topic, name='new_topic'),
	#Strona do dodawania wpisow przez uzytkownika
	path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
	# Strona przeznaczona do edycji wpisu
	path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),



]

users/urls.py
"""Definiuje wzorce adresow URL dla aplikacji users."""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
	# Dolaczenie domyslnych adresow URL uwierzytelniania
	path('', include('django.contrib.auth.urls')),
	# Strona rejestracji
	path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
	"""Temat poznawany przez uzytkownika"""
	text = models.CharField(max_length = 200)
	date_added = models.DateTimeField(auto_now_add = True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)


	def __str__(self):
		"""Zwraca reprezentacje modelu w postaci ciagu tekstowego"""
		return self.text


class Entry(models.Model):
	"""Konkretne informacje o postepie w nauce"""
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add = True)


	class Meta:
		verbose_name_plural = 'entries'
		

	def __str__(self):
		"""Zwraca reprezentacje modelu w postaci ciagu tekstowego."""
		if len(self.text) > 50:
			return f"{self.text[:50]}..."
		else:
			return f"{self.text}"

		

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text': ''}


class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text': ''}
		idgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404

from .models import Topic, Entry 
from .forms import TopicForm, EntryForm


def index(request):
	"""Strona glowna dla aplikacji Learning Log."""
	return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
	"""Wyswietlenie wszystkich tematow."""
	topics = Topic.objects.filter(owner=request.user).order_by('date_added')
	context = {'topics': topics}
	return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
	"""Wyswietla pojedynczy temat i wszystkie powiazane  nim wpisy."""
	topic = get_object_or_404(Topic, id=topic_id)
	# Upewniamy	 sie ze temat nalezy do biezacego uzytkownika
	if topic.owner != request.user:
		raise Http404

	entries = topic.entry_set.order_by('-date_added')
	context = {'topic':topic, 'entries':entries}
	return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
	"""Dodaj nowy temat."""
	if request.method != 'POST':
		#Nie przekazano zadnych danych, nalezy utworzyc pusty formularz
		form = TopicForm()
	else:
		#Przekazano dane za pomoca zadania POST, nalezy je przetworzyc
		form = TopicForm(data=request.POST)
		if form.is_valid():
			new_topic = form.save(commit=False)
			new_topic.owner = request.user
			form.save()
			return redirect('learning_logs:topics')

	#Wyswietlenie pustego formularza
	context = {'form': form}
	return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
	"""Dodanie nowego wpisu dla okreslonego tematu."""
	topic = Topic.objects.get(id=topic_id)

	if request.method != 'POST':
		# Nie przekazano zadnych danych, nalezy utworzyc pusty formularz
		form = EntryForm()
	else:
		# Przekazano dane za pomoca zadania POST, nalezy je przetworzyc
		form = EntryForm(data=request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			new_entry.save()
			return redirect('learning_logs:topic', topic_id=topic_id)

		# Wyswietlenie pustego formularza
	context = {'topic': topic, 'form': form}
	return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
	"""Edycja istniejacego wpisu."""
	entry = Entry.objects.get(id=entry_id)
	topic = entry.topic

	if topic.owner != request.user:
		raise Http404

	if request.method != 'POST':
		# Zadanie poczatkowe, wypelnienie formularza aktualna trescia wpisu
		form = EntryForm(instance=entry)
	else:
		# PRzekazano dane za pomoca zadania POST, nalezy je przetworzyc
		form = EntryForm(instance=entry, data=request.POST)
		if form.is_valid():
			form.save()
			return redirect('learning_logs:topic', topic_id=topic.id)

	context = {'entry': entry, 'topic': topic, 'form': form}
	return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
	"""Rejestracja nowego uzytkowanika."""
	if request.method != 'POST':
		# Wyswietlanie pustego formularza rejestracji uzytkownika.
		form = UserCreationForm()
	else:
		# Przetworzenie wypelnionego formularza.
		form = UserCreationForm(data=request.POST)
		if form.is_valid():
			new_user = form.save()
			# Zalogowanie uzytkownika, a nastepnie przekierowanie go na strone glowna
			login(request, new_user)
			return redirect('learning_logs:index')

	# Wyswietlenie pustego formularza
	context = {'form': form}
	return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="pl">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

  </head>


  <body>
    
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4border">

      <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>

      <button class="navbar-toggler"
              type="button"
              data-toggle="collapse" 
              data-target="#navbarCollapse"
              aria-controls="navbarCollapse"
              aria-expanded="false"
              aria-label="Toggle navigation">

      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'learning_logs:topics' %}">Tematy</a></li>
      </ul>

      <ul class="navbar-nav ml-auto">

        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text">Witaj, {{ user.username }}.</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Wyloguj</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Rejestruj</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}"> Zaloguj</a>
          </li>
        {% endif %}
      </ul>
    </div>

  </nav>


  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>


  </body>
  </html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block content %}

<div class="p-1 mb-0 bg-dark text-white" align="center">
  <p>Edytujesz wpis w temacie: <a href="{% url 'learning_logs:topic' topic.id %}" class="link-dark">{{ topic }}</a></p>
</div>

<div class="p-3 mb-0 bg-light text-dark:">
  <label for="newEntryInput">Edycja wpisu:</label>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' class="form">
    <small id="entryHelp" class="form-text text-muted">Maksymalna dlugosc wpisu to 500 znakow.</small>
    {% bootstrap_form form %}
    {% csrf_token %}
    
    {% buttons %}
    <button type="submit" class="btn btn-outline-primary">Zapisz zmiany</button>
    {% endbuttons %}
  </form>
</div>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <div class="jumbotron">
  	<h1 class="display-3">Monitoruj postepy w nauce</h1>

  	<p class="lead">Zaloz konto, aby rozpoczac korzystanie z aplikacji Learning Log oraz wyswietlic liste poznawanych tematow. Gdy nauczysz sie czegos nowego na dany temat, utworz wpis podsumowujacy to, czego sie nauczyles.</p>

  	<a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Zarejestruj konto &raquo;</a>
  </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block content %}

<div class="p-1 mb-0 bg-dark text-white" align="center">
  <p>Dodajesz wpis w temacie: <a href="{% url 'learning_logs:topic' topic.id %}" class="link-dark">{{ topic }}</a></p>
</div>


<div class="p-3 mb-0 bg-light text-dark:">
  <label for="newEntryInput">Dodaj nowy wpis:</label>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' class="form">
    <small id="entryHelp" class="form-text text-muted">Maksymalna dlugosc wpisu to 500 znakow.</small>
    {% bootstrap_form form %}
    {% csrf_token %}
    
    {% buttons %}
    <button type="submit" class="btn btn-outline-primary">Dodaj wpis</button>
    {% endbuttons %}
  </form>
</div>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
<p>Dodaj nowy temat</p>

<form action="{% url 'learning_logs:new_topic' %}" method='post'>
  {% csrf_token %}
  {{ form.as_p }}
  <button name="submit">Dodaj temat</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
  <h2>{{ topic }}</h2>
{% endblock page_header %}

{% block content %}

<p>
  <a href="{% url 'learning_logs:new_entry' topic.id %}">Dodaj nowy wpis</a>
</p>

{% for entry in entries %}
  <div class="card mb-3">
    <h4 class="card-header">
      {{ entry.date_added|date:'d M Y H:i' }}
        <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">Edytuj wpis</a></small>
    </h4>
    <div class="card-body">
      {{ entry.text|linebreaks }}
    </div>
  </div>
  {% empty %}
    Nie ma jeszcze zadnego wpisu dla tematu.
  {% endfor %}  

{% endblock content %}
  

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h1>Tematy</h1>
{% endblock page_header %}


{% block content %}

  <ul>
  	{% for topic in topics %}
  	  <li><h3>
  	  	<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
  	  </h3></li>
  	{% empty %}
  	  <li><h3>Nie zostal jeszcze dodany zaden temat.</h3></li>
  	{% endfor %}
  </ul>

  <h3><a href="{% url 'learning_logs:new_topic' %}">Dodaj Nowy temat</h3>

{% endblock content %}